### ISSUE TITLE
BigQuery: Hente inn datasett for alle arbeidstakersøknader

### ISSUE THREAD

**Issue by chsko** [navikt/helse-dataprodukter#1]
Vi trenger alle arbeidstakersøknader i BigQuery for å kunne svare ut Spleiselagets KR0: Synkende annulleringstrend. Dataen produseres allerede av appen førstegangsbehandling, men hentes i dag ikke til BigQuery

**Comment by fraadsbrandth** [comment]
Dette blir gøy 🦄
